---
- hosts: onos-master
  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"
  become: yes
  vars_files:
    - group_vars/config.yml
  roles:
    - quagga_config
    - gobgp_config
    - sdnip_netcfg
    - sdnip_topo
