---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script:
  # We'll add some commands to test the role here.
  - ansible-playbook -i ci_test/local_inventory provisioning/basic/playbook.yml --syntax-check
  - ansible-playbook -i ci_test/local_inventory provisioning/docker/playbook.yml --syntax-check
  - ansible-playbook -i ci_test/local_inventory provisioning/onos/playbook.yml --syntax-check
  - ansible-playbook -i ci_test/local_inventory provisioning/mininet/playbook.yml --syntax-check
  - ansible-playbook -i ci_test/local_inventory provisioning/quagga/playbook.yml --syntax-check
  - ansible-playbook -i ci_test/local_inventory provisioning/sdnip/playbook.yml --syntax-check
  - ansible-playbook -i ci_test/local_inventory provisioning/gobgp/playbook.yml --syntax-check
  - ansible-playbook -i ci_test/local_inventory provisioning/ryu/playbook.yml --syntax-check
