---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"
  become: yes
  become_method: sudo
  vars_files:
    - group_vars/config.yml
    - group_vars/versions.yml
  roles:
    - ryu
    - sdnip
