---
- name: Check docker status
  shell: systemctl status docker

- name: Add vagrant to docker group
  user:
    name: vagrant
    groups: docker,sudo
    append: yes

- name: Pull basic Docker image
  docker_image:
    name: ubuntu
