---
- name: Update APT Cache
  apt:
    update_cache: yes
  tags: docker

- name: Add key
  apt_key:
    key_server: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  tags: docker

- name: Add Docker APT Repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
  tags: docker

- name: Update APT Cache
  apt:
    update_cache: yes
  tags: docker

- name: Policy apt cache
  shell: apt-cache policy docker-engine
  tags: docker

- name: install Docker
  apt:
    name: docker-engine
    state: present
  tags: docker
