---
- name: Make quagga configuration dir
  file:
    path="{{ QUAGGA_CONFIG_PATH }}"
    state=directory

- name: Make zebra configuration dir
  file:
    path="{{ ZEBRA_CONFIG_PATH }}"
    state=directory

- name: Copy default quagga configuration files
  template:
    src: "templates/{{ item }}"
    dest: "{{ QUAGGA_CONFIG_PATH }}/{{ item }}"
    mode: 0644
  with_items:
    - quagga_amlight.conf
    - quagga_internal_1.conf
    - quagga_internal_2.conf
    - quagga_kreonet.conf
  tags: quagga

- name: Copy zebra configuration file
  template:
    src: "templates/{{ item }}"
    dest: "{{ ZEBRA_CONFIG_PATH }}/{{ item }}"
    mode: 0644
  with_items:
    - "zebra.conf"
    - "zebra_amlight.conf"
    - "zebra_kreonet.conf"
  tags: quagga

- name: Make /root readable for vty
  file:
    path: /root
    mode: 0755
  tags: quagga
