---
- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python2.7"
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - group_vars/config.yml
    - group_vars/version.yml
  roles:
    - golang
    - gobgp
