---
- hosts: onos-master
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  sudo: yes
  vars_files:
    - group_vars/config.yml
    - group_vars/version.yml
  roles:
    - golang
    - gobgp
