---
- name: Download Quagga
  get_url:
    dest: {{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}.tar.gz
    url: http://download.savannah.gnu.org/releases/quagga/quagga-{{ QUAGGA_VER }}.tar.gz
  tags: quagga

- name: Unarchive Quagga
  unarchive:
    copy: no
    dest: {{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}
    src: {{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}.tar.gz
  tags: quagga

- name: Configure Quagga
  shell: ./configure
  args:
    chdir: {{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}
  tags: quagga

- name: Build Quagga
  shell: make
  args:
    chdir: {{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}
  tags: quagga

- name: Install Quagga
  shell: make install
  args:
    chdir: {{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}
  tags: quagga

- name: Copy default quagga configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ QUAGGA_CONFIG_PATH },}/{{ item }}.j2"
    mode: 0644
  with_items:
    - quagga_anlight.conf
    - quagga_internal_1.conf
    - quagga_internal_2.conf
    - quagga_krenet.conf
  tags: quagga

- name: Copy zebra configuration file
  template:
    src: zebra.conf.j2
    dest: "{{ ZEBRA_CONFIG_PATH }}"
    mode: 644
  tags: quagga
