---
- name: Download Quagga
  get_url:
    dest: "{{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}.tar.gz"
    url: "http://download.savannah.gnu.org/releases/quagga/quagga-{{ QUAGGA_VER }}.tar.gz"
  tags: quagga

- name: Unarchive Quagga
  unarchive:
    copy: no
    dest: "{{ APP_PATH }}"
    src: "{{ DOWNLOADS_PATH }}/quagga-{{ QUAGGA_VER }}.tar.gz"
  tags: quagga

- name: Configure Quagga
  shell: ./configure
  args:
    chdir: "{{ APP_PATH }}/quagga-{{ QUAGGA_VER }}"
  tags: quagga

- name: Build Quagga
  shell: make
  args:
    chdir: "{{ APP_PATH }}/quagga-{{ QUAGGA_VER }}"
  tags: quagga

- name: Install Quagga
  shell: make install
  args:
    chdir: "{{ APP_PATH }}/quagga-{{ QUAGGA_VER }}"
  tags: quagga
- name: Make quagga configuration dir
  file:
    path="{{ QUAGGA_CONFIG_PATH }}"
    state=directory

- name: Make zebra configuration dir
  file:
    path="{{ ZEBRA_CONFIG_PATH }}"
    state=directory

- name: Copy default quagga configuration files
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ QUAGGA_CONFIG_PATH }}/{{ item }}"
    mode: 0644
  with_items:
    - quagga_amlight.conf
    - quagga_internal_1.conf
    - quagga_internal_2.conf
    - quagga_krenet.conf
  tags: quagga

- name: Copy zebra configuration file
  template:
    src: "templates/zebra.conf.j2"
    dest: "{{ ZEBRA_CONFIG_PATH }}/zebra.conf"
    mode: 644
  tags: quagga
